In [2]:
import numpy as np

In [3]:
list = np.array([1,2,3,4])
list

array([1, 2, 3, 4])

In [12]:
ran_list = np.arange(100000)

In [5]:
list.shape

(4,)

In [8]:
list ** 2

array([ 1,  4,  9, 16])

In [9]:
np.mean(list)

2.5

In [11]:
np.sum(list)

10

In [16]:
ran_list[:10] ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [24]:
twod = np.array([[1,2,3],[4,5,6]])

In [27]:
oned = np.array([1,2,3,4,5,6])

In [31]:
threed = np.array([[[1,2],[3,4]],[[6,7],[4,5]],[[2,4],[5,6]]])

In [33]:

threed

array([[[1, 2],
        [3, 4]],

       [[6, 7],
        [4, 5]],

       [[2, 4],
        [5, 6]]])

In [35]:
for i in threed:
    print(np.sum(i))

10
22
17


In [37]:
print(oned.ndim)
print(twod.ndim)
print(threed.ndim)

1
2
3


In [42]:
print(oned.shape)
print(twod.shape)
print(threed.shape)

(6,)
(2, 3)
(3, 2, 2)


In [43]:
print(oned.size)
print(twod.size)
print(threed.size)

6
6
12


In [50]:
shape = (4,3,2)
z = np.zeros(shape)

In [51]:
z.astype('int64')

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0]]], dtype=int64)

In [54]:
shape = (4,3,3)
np.ones((2,3,3),dtype = 'int32')

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]])

In [100]:
ran = np.random.randint(1,100)
ran

32

In [136]:
rand_list = np.zeros((2,3),dtype = 'int32')
for i in rand_list:
    for j in i:
        j = np.random.randint(1,100)
        print(j)
rand_list

42
51
71
20
20
39


array([[0, 0, 0],
       [0, 0, 0]])

In [105]:
np.full((2,3),67)

array([[67, 67, 67],
       [67, 67, 67]])

In [107]:
list

array([1, 2, 3, 4])

In [131]:
n = np.random.rand(4,5) * 100
n.astype('int16')

array([[43, 89, 90, 19, 33],
       [14, 64, 42, 73, 76],
       [42, 43, 18, 93, 84],
       [85, 67, 20, 57, 65]], dtype=int16)

In [133]:
list[1] = 4
list[1]

4

In [140]:
np.array([[np.arange(2,5)],[np.arange(5,8)]])

array([[[2, 3, 4]],

       [[5, 6, 7]]])

In [142]:
np.array([[np.linspace(2,10,5, dtype=int)],[np.linspace(5,20,5, dtype = int)]])

array([[[ 2,  4,  6,  8, 10]],

       [[ 5,  8, 12, 16, 20]]])

In [148]:
lis = np.ones((5,5), dtype = 'int32')
liszero = np.zeros((3,3), dtype ='int32')
lis[1:4,1:4] = liszero
lis[2,2] = 9
lis
    

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 9, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

In [149]:
twod

array([[1, 2, 3],
       [4, 5, 6]])

In [155]:
twod[1,2]

6

In [156]:
threed

array([[[1, 2],
        [3, 4]],

       [[6, 7],
        [4, 5]],

       [[2, 4],
        [5, 6]]])

In [167]:
np.mean(oned)

3.5

In [164]:
np.cumsum(oned)

array([ 1,  3,  6, 10, 15, 21])

In [168]:
a=10
b=5
np.subtract(a,b)

5

In [178]:
twod

array([[1, 2, 3],
       [4, 5, 6]])

In [180]:
np.min(twod, axis = 1)

array([1, 4])

In [185]:
twod.reshape((3,2))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [189]:
twod

array([[1, 2, 3],
       [4, 5, 6]])

In [191]:
np.argmin(twod,axis = 1)

array([0, 0], dtype=int32)

In [194]:
a = np.ones((2,3))
b = np.full((3,2),3)

In [197]:
print(a)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[3 3]
 [3 3]
 [3 3]]


In [198]:
np.matmul(a,b)

array([[9., 9.],
       [9., 9.]])

A = [a11 a12]
    [a21 a22]
B = [b11 b12]
    [b21 b22]

C = A * B

C = [c11 c12]
    [c21 c22]

c11 = a11*b11 + a12*b21
c12 = a11*b12 + a12*b22
c21 = a21*b11 + a22*b21
c22 = a21*b12 + a22*b22
