In [ ]:
# 68) Create a null vector of size 10

In [ ]:
# 67) How to find the memory size of any array 

In [ ]:
# 66) Create a null vector of size 10 but the fifth value which is 1

In [ ]:
# 65) Create a vector with values ranging from 10 to 49

In [ ]:
# 64) Reverse a vector (first element becomes last)

In [ ]:
# 63) Create a 3x3 matrix with values ranging from 0 to 8

In [ ]:
# 62) Create a 3x3 identity matrix

In [ ]:
# 61) Create a 3x3x3 array with random values

In [ ]:
# 60) Create a 2d array with 1 on the border and 0 inside

In [11]:
# What is the result of the following expression?
# 0 * np.nan
# np.nan == np.nan
# np.inf > np.nan
# np.nan - np.nan
# np.nan in set([np.nan])
# 0.3 == 3 * 0.1

In [ ]:
##########################################################################

In [9]:
# 59) Count the number of elements in an array that are greater than the mean.

In [ ]:
# 58) Create a 2D array with random integers and replace all values greater than a certain threshold with that threshold.

In [ ]:
# 57) Check if any element in a 1D array is non-zero.

In [ ]:
# 56) Compute the cumulative sum of elements along a given axis in a 2D array.

In [ ]:
# 55) Compute the cumulative product of elements along a given axis in a 2D array.

In [ ]:
# 54) Replace all even numbers in a 1D array with the next odd number.

In [ ]:
# 53) Calculate the element-wise square of the difference between two arrays.

In [ ]:
# 52) Calculate the pairwise Euclidean distance between two arrays.

In [ ]:
# 51) Compute the sum of diagonal elements in a 2D array.

In [ ]:
# 50) Calculate the mean of each row in a 2D array ignoring nan values.
matrix = np.array([[1, 2, np.nan], [4, np.nan, 6], [7, 8, 9]])

In [ ]:
# 49) Create a 2D array and replace all nan values with the mean of the array.
matrix = np.array([[1, np.nan, 3], [4, 5, np.nan], [7, 8, 9]])

In [ ]:
# 48) Find the indices of the maximum value in each row of a 2D array.
matrix = np.random.random((3, 4))

In [1]:
# 47) Check if all elements in a 1D array are non-zero.
arr = np.array([1, 2, 3, 4, 5])

In [ ]:
# 46) Convert the elements of a 1D array to strings.

In [ ]:
# 45) Find the indices of the top N minimum values in a 1D array.

In [ ]:
# 44) Create a 2D array with random values and replace the maximum value in each row with -1.

In [ ]:
# 43) Calculate the element-wise absolute difference between two arrays.

In [ ]:
# 42) Create a 1D array and append a new element to the end.

In [ ]:
# 41) Round elements of a 1D array to the nearest integer.
arr = np.array([1.2, 2.7, 3.5, 4.9])

In [ ]:
# 40) Count the number of occurrences of each unique value in a 1D array.

In [ ]:
# 39) Create a 3x3 matrix and set all values above the main diagonal to zero.

In [ ]:
# 38) Create a 1D array and set the values between 10 and 20 to 0.

In [ ]:
# 37) Compute the matrix multiplication of two 2D arrays.

In [155]:
# 36) Create a 2D array with random values and replace the maximum value with the minimum.


array([[ 1,  2,  3],
       [ 4,  1, 10],
       [ 8,  6,  2]])

In [ ]:
# 35) Calculate the element-wise exponentiation of a 1D array.

In [ ]:
# 34) Calculate the determinant of a 3x3 matrix.


In [147]:
# 33) Create a random 2D array and sort it by the second column.
matrix = np.array([[1, 2,3], [4, 15,10],[8,6,2]])


[[ 1  2  3]
 [ 4 15 10]
 [ 8  6  2]]


array([[ 1,  2,  3],
       [ 8,  6,  2],
       [ 4, 15, 10]])

In [133]:
# 32) Create a 1D array with 10 equidistant values between 0 and 1.


array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [132]:
# 31) Create a 2D array and set all values above a certain threshold to that threshold.
arr1 = np.array([[1, 2,3], [4, 5,10]])
threshold = 3


array([[1, 2, 3],
       [3, 3, 3]])

In [129]:
# 30) Create a 1D array and remove all duplicate values.
arr1 = np.array([1, 2, 3, 4,5, 4, 5])


array([1, 2, 3, 4, 5])

In [128]:
# 29) compute product of all the elemets of the array
arr1 = np.array([[1, 2,3], [4, 5,10]])


(1200, array([ 4, 10, 30]), array([  6, 200]))

In [122]:
# 28) Compute the element-wise product of two arrays.
arr1 = np.array([[1, 2,], [4, 5]])
arr2 = np.array([[3, 2,],[8, 5]])


[[1 2]
 [4 5]]
[[3 2]
 [8 5]]


40

In [111]:
#27) Create a 2D array and replace all nan values with 0.
matrix = np.array([[1, np.nan, 3], [4, 5, np.nan], [7, 8, 9]])


array([[1., 0., 3.],
       [4., 5., 0.],
       [7., 8., 9.]])

In [110]:
# 26) Count the number of non-zero elements in a 2D array.
arr = np.array([[0, 77,  0],
               [ 6, 0,  5],
               [ 0,  1,  0]])


4

In [107]:
# 25) Find the indices where elements of two arrays match.
import numpy as np
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([3, 2, 8, 4, 5])


[1, 3, 4]

In [104]:
# 24) Calculate the square root of each element in a 1D array.
arr = np.array([1, 2, 3, 4, 5, 5, 64])


array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.23606798, 8.        ])

In [102]:
# 23) Count the number of elements in an array that are greater than the mean.
arr = np.array([1, 2, 3, 4, 5, 5])


3

In [93]:
# 22) Convert the data type of an array to float.
arr = np.array([-1, 2, -3, 4, -5])


array([-1.,  2., -3.,  4., -5.])

In [92]:
# 21) Replace all negative values in an array with 0
arr = np.array([-1, 2, -3, 4, -5])


array([0, 2, 0, 4, 0])

In [91]:
# 20) Create a 2D array with random values and sort each column in descending order.


array([[10, 77,  8],
       [ 6, 40,  5],
       [ 3,  1,  2]])

In [80]:
# 19) Create a 2D array with random values and sort each row in descending order.
arr = np.array([[10, 1, 2],
       [3, 40, 5],
       [6, 77, 8]])
sorted_arr = np.sort(arr,axis = 1)
print(sorted_arr)
sorted_arr[:,::-1]

[[ 1  2 10]
 [ 3  5 40]
 [ 6  8 77]]


array([[10,  2,  1],
       [40,  5,  3],
       [77,  8,  6]])

In [68]:
# 18) Calculate the mean of each column in a 2D array.
np.mean(arr, axis = 0)

array([0.44124627, 0.56114851, 0.26507591])

In [67]:
# 17) Create a random 3x3 matrix and replace all values greater than 0.5 with 1 and all others with 0.
arr = np.random.rand(3,3)
print(arr)
np.where(arr>0.5,1,0)

[[0.21967536 0.52073656 0.1623635 ]
 [0.82623917 0.17227884 0.28840638]
 [0.2778243  0.99043015 0.34445784]]


array([[0, 1, 0],
       [1, 0, 0],
       [0, 1, 0]])

In [65]:
# 16) Swap two rows in a 2D array.
arr = np.array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

arr[[0,2],:] = arr[[2,0],:]
arr

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [57]:
# 15) Create a 3x3 matrix with values ranging from 0 to 8.
np.arange(9).reshape(3,3)
np.linspace(0,8,9).reshape(3,3).astype('int16')

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]], dtype=int16)

In [53]:
# 14) Find the unique values and their counts in a 1D array.
arr = np.array([1, 2, 3, 2, 4, 1, 5, 4, 6])
values,counts = np.unique(arr,return_counts=True)
dict(zip(values,counts))

{1: 2, 2: 2, 3: 1, 4: 2, 5: 1, 6: 1}

In [51]:
# 13) Find the indices of the maximum and minimum values in a 1D array.
arr = np.array([5, 2, 8, 1, 7])
print(np.argmax(arr))
print(np.argmin(arr))

2
3


In [45]:
# 12) Replace all values in a 1D array with the mean of the array.
arr = np.array([5, 2, 8, 0, 7])
# np.where(arr, np.mean(arr), 0)

np.full(arr.shape, np.mean(arr))

array([4.4, 4.4, 4.4, 4.4, 4.4])

In [38]:
# 11) Create a random 4x4 matrix and extract the diagonal elements.
import numpy as np
matrix = np.random.random((4, 4))
print(matrix)
np.diag(matrix)

[[0.26379705 0.86179403 0.06540035 0.92462774]
 [0.12364527 0.95660927 0.8360032  0.79495511]
 [0.25712076 0.79700226 0.06374284 0.72738004]
 [0.86902388 0.63077932 0.56417534 0.45265638]]


array([0.26379705, 0.95660927, 0.06374284, 0.45265638])

In [36]:
# 10) Find the mean of each row in a 2D array.
matrix = np.random.random((3, 4))
np.mean(matrix, axis = 1)

array([0.30367756, 0.39665621, 0.75196848])

In [34]:
# 9) Stack two arrays vertically.
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
np.vstack([arr1,arr2])

array([[1, 2, 3],
       [4, 5, 6]])

In [28]:
# 8) Reshape a 1D array to a 2D array with 5 rows and 2 columns.
arr = np.arange(10)
arr.reshape((5,2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [27]:
# 7) Create a 3x3 identity matrix.
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [26]:
# 6) Reverse a 1D array (first element becomes the last).
arr = np.arange(5)
# arr[::-1]

# np.flip(arr)

array([4, 3, 2, 1, 0])

In [23]:
# 5) Find the indices of non-zero elements.
arr = np.array([[1,2,0],[0,4,0],[5,0,10]])
row,col = np.where(arr > 0)
list(zip(row,col))

[(0, 0), (0, 1), (1, 1), (2, 0), (2, 2)]

In [17]:
# 4. Create a random 3x3 matrix and normalize it.
arr = np.random.rand(3,3)
arr_norm = (arr - np.mean(arr))/np.std(arr)
arr_norm

array([[-0.27960648, -1.73151113, -1.33244186],
       [ 0.6224684 ,  1.12270793,  0.78248894],
       [ 0.78216432, -0.78179308,  0.81552296]])

In [14]:
# 3. Replace all even numbers in a 1D array with their negative.
arr = np.arange(1,11)
np.where(arr % 2 == 0, arr*-1, arr)

array([  1,  -2,   3,  -4,   5,  -6,   7,  -8,   9, -10])

In [13]:
# 2. Convert a 2D array to a boolean array where all positive values become True.

arr = np.array([[1,-6,5,4],[-7,3,-8,-2]])
# arr > 0

# np.where(arr >0, True, False)

array([[ True, False,  True,  True],
       [False,  True, False, False]])

In [10]:
# 1. Replace all odd numbers in an array of 1-10 with -1.
arr = np.arange(1,11)
np.where(arr%2 != 0,-1, arr)

array([-1,  2, -1,  4, -1,  6, -1,  8, -1, 10])