<a href="https://colab.research.google.com/github/Mr-Hackrr/notebook/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [44]:
import numpy as np

In [2]:
list = np.array([1,2,3,4])
list

array([1, 2, 3, 4])

In [3]:
ran_list = np.arange(100000)

In [4]:
list.shape

(4,)

In [5]:
list ** 2

array([ 1,  4,  9, 16])

In [6]:
np.mean(list)

2.5

In [7]:
np.sum(list)

10

In [8]:
ran_list[:10] ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [9]:
twod = np.array([[1,2,3],[4,5,6]])

In [10]:
oned = np.array([1,2,3,4,5,6])

In [11]:
threed = np.array([[[1,2],[3,4]],[[6,7],[4,5]],[[2,4],[5,6]]])

In [12]:

threed

array([[[1, 2],
        [3, 4]],

       [[6, 7],
        [4, 5]],

       [[2, 4],
        [5, 6]]])

In [13]:
for i in threed:
    print(np.sum(i))

10
22
17


In [14]:
print(oned.ndim)
print(twod.ndim)
print(threed.ndim)

1
2
3


In [15]:
print(oned.shape)
print(twod.shape)
print(threed.shape)

(6,)
(2, 3)
(3, 2, 2)


In [16]:
print(oned.size)
print(twod.size)
print(threed.size)

6
6
12


In [17]:
shape = (4,3,2)
z = np.zeros(shape)

In [18]:
z.astype('int64')

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0]]])

In [19]:
shape = (4,3,3)
np.ones((2,3,3),dtype = 'int32')

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]], dtype=int32)

In [20]:
ran = np.random.randint(1,100)
ran

93

In [21]:
rand_list = np.zeros((2,3),dtype = 'int32')
for i in rand_list:
    for j in i:
        j = np.random.randint(1,100)
        print(j)
rand_list

6
51
43
69
85
92


array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [22]:
np.full((2,3),67)

array([[67, 67, 67],
       [67, 67, 67]])

In [23]:
list

array([1, 2, 3, 4])

In [24]:
n = np.random.rand(4,5) * 100
n.astype('int16')

array([[65, 34, 35, 26, 33],
       [96, 45, 22, 96, 31],
       [67,  8, 97, 33, 68],
       [35, 43, 55, 25, 18]], dtype=int16)

In [25]:
list[1] = 4
list[1]

4

In [26]:
np.array([[np.arange(2,5)],[np.arange(5,8)]])

array([[[2, 3, 4]],

       [[5, 6, 7]]])

In [27]:
np.array([[np.linspace(2,10,5, dtype=int)],[np.linspace(5,20,5, dtype = int)]])

array([[[ 2,  4,  6,  8, 10]],

       [[ 5,  8, 12, 16, 20]]])

In [28]:
lis = np.ones((5,5), dtype = 'int32')
liszero = np.zeros((3,3), dtype ='int32')
lis[1:4,1:4] = liszero
lis[2,2] = 9
lis


array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 9, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]], dtype=int32)

In [29]:
twod

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
twod[1,2]

6

In [31]:
threed

array([[[1, 2],
        [3, 4]],

       [[6, 7],
        [4, 5]],

       [[2, 4],
        [5, 6]]])

In [32]:
np.mean(oned)

3.5

In [33]:
np.cumsum(oned)

array([ 1,  3,  6, 10, 15, 21])

In [34]:
a=10
b=5
np.subtract(a,b)

5

In [35]:
twod

array([[1, 2, 3],
       [4, 5, 6]])

In [36]:
np.min(twod, axis = 1)

array([1, 4])

In [37]:
twod.reshape((3,2))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [38]:
twod

array([[1, 2, 3],
       [4, 5, 6]])

In [39]:
np.argmin(twod,axis = 1)

array([0, 0])

In [40]:
a = np.ones((2,3))
b = np.full((3,2),3)

In [41]:
print(a)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[3 3]
 [3 3]
 [3 3]]


In [42]:
np.matmul(a,b)

array([[9., 9.],
       [9., 9.]])

A = [a11 a12]
    [a21 a22]
B = [b11 b12]
    [b21 b22]

C = A * B

C = [c11 c12]
    [c21 c22]

c11 = a11*b11 + a12*b21
c12 = a11*b12 + a12*b22
c21 = a21*b11 + a22*b21
c22 = a21*b12 + a22*b22


In [57]:
# prompt: numpy.genfromtxt example code

import numpy as np
file_path = '/content/sample_data/mnist_test.csv'

# Read a simple comma-separated file:
data = np.genfromtxt(file_path, delimiter=',')
print(data[:1])

[[  7.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   

In [64]:
data1 = np.array([12,14,15,33,45,67,89,45])
data1

array([12, 14, 15, 33, 45, 67, 89, 45])

In [68]:
np.where(data1>67)

(array([6]),)

In [66]:
np.where(data1>5,data1,0)

array([12, 14, 15, 33, 45, 67, 89, 45])

In [72]:
list = (1,2.3,3,4.7,5,6,7,8,9,10)
np.cumsum(list)

array([ 1. ,  3.3,  6.3, 11. , 16. , 22. , 29. , 37. , 46. , 56. ])

In [73]:
# prompt: convert a 2d array into a boolean array where positive values become true

import numpy as np

# Create a 2D array
array = np.array([[1, -2, 3], [-4, 5, -6]])

# Convert positive values to True
bool_array = array > 0

# Print the boolean array
print(bool_array)


[[ True False  True]
 [False  True False]]


In [75]:
l1 = np.arange(1,11)
np.where(l1%2==0,l1*-1,l1)

array([  1,  -2,   3,  -4,   5,  -6,   7,  -8,   9, -10])

In [76]:
arr = np.random.rand(3,3)
arr_norm = (arr - np.mean(arr))/np.std(arr)
arr_norm

array([[-0.0492723 ,  0.12976633, -0.76683128],
       [ 0.86697317, -1.1345785 , -0.12429296],
       [ 1.39586332,  1.31418731, -1.63181508]])

In [90]:
# prompt: find the indices of non xero elemets in 2d array

# Create a 2D array
array = np.array([[0, 1, 0], [2, 0, 3], [0, 4, 0]])

# Find the indices of non-zero elements
r,c = np.where(array>0)
print(r)
print(c)




[0 1 1 2]
[1 0 2 1]


In [97]:
arr2 = np.array([5,2,8,1,7])
np.full(arr2.shape,np.mean(arr2))

array([4.6, 4.6, 4.6, 4.6, 4.6])

In [99]:
# prompt: find the unique values and their counts in 1d array using numpy

# Create a 1D array
array = np.array([1, 2, 3, 4, 2, 5, 1, 6, 3, 4])

# Find the unique values and their counts
unique_values, counts = np.unique(array, return_counts=True)

dict(zip(unique_values,counts))
# Print the unique values and their counts
# for i in range(len(unique_values)):
#   print(f"Unique value: {unique_values[i]}, Count: {counts[i]}")


{1: 2, 2: 2, 3: 2, 4: 2, 5: 1, 6: 1}

In [101]:
np.arange(0,9).reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [102]:
twod

array([[1, 2, 3],
       [4, 5, 6]])

In [107]:

twod[[0,1]] = twod[[1,0]]
twod

array([[4, 5, 6],
       [4, 5, 6]])

In [ ]:
# prompt: swap two rows in 2d array

import numpy as np

# Create a 2D array
twod = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(twod)

# Swap two rows
twod[[0, 1]] = twod[[1, 0]]

# Print the modified array
print(twod)


In [ ]:
# prompt: generate some coding question on numpy

# 1. Given a 2D array of integers, find the sum of all elements in the array.

# 2. Given a 1D array of integers, find the mean, median, and standard deviation of the array.

# 3. Given a 2D array of integers, find the maximum and minimum values in each row of the array.

# 4. Given a 3D array of integers, find the sum of all elements in the array that are greater than a given threshold.

# 5. Given a 2D array of integers, find the indices of all elements that are equal to a given value.

# 6. Given a 1D array of integers, create a new array that contains the square of each element in the original array.

# 7. Given a 2D array of integers, create a new array that contains the sum of each row in the original array.

# 8. Given a 3D array of integers, create a new array that contains the maximum value in each column of the original array.

# 9. Given a 2D array of integers, create a new array that contains the transpose of the original array.

# 10. Given a 1D array of integers, create a new array that contains the elements of the original array in reverse order.


In [ ]:
# prompt: create a 2d array with random values and sort each row in desending order

import numpy as np

# Create a 2D array with random values
arr = np.random.randint(1, 100, size=(5, 5))

# Sort each row in descending order
arr = np.sort(arr, axis=1)[::-1]

# Print the sorted array
print(arr)
